# yaml-language-server: $schema=https://goreleaser.com/static/schema.json
version: 2

before:
  hooks:
    - go mod tidy
    - go test ./...

# For Go libraries, we typically don't need binary builds
# Instead, we focus on source code releases and proper tagging
builds:
  - skip: true

# Skip archives since this is a library, not a binary distribution
archives:
  - formats: [tar.gz]
    files:
      - none*

changelog:
  sort: asc
  use: github
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^chore:"
      - "^ci:"
  groups:
    - title: Features
      regexp: "^.*feat[(\\w)]*:+.*$"
      order: 0
    - title: 'Bug fixes'
      regexp: "^.*fix[(\\w)]*:+.*$"
      order: 1
    - title: Others
      order: 999

release:
  github:
    owner: BrunoKrugel
    name: echo-swagger
  draft: false
  prerelease: auto
  mode: replace
  header: |
    ## echo-swagger {{ .Tag }}

    This release contains the latest version of echo-swagger, a echo middleware to automatically generate RESTful API documentation with Swagger 2.0.

    ### Installation

    ```bash
    go get github.com/BrunoKrugel/echo-swagger@{{ .Tag }}
    ```

  footer: |
    ## Usage

    Import the library in your Go project:

    ```go
    import "github.com/BrunoKrugel/echo-swagger"
    ```

    For detailed usage examples, see the [examples](https://github.com/BrunoKrugel/echo-swagger/blob/main/examples/v3/main.go) directory.

    ---

    **Full Changelog**: https://github.com/BrunoKrugel/echo-swagger/compare/{{ .PreviousTag }}...{{ .Tag }}

    Released by [GoReleaser](https://github.com/goreleaser/goreleaser).
